支持复杂项目
coolme200/webstorm-disable-index pull request #7
Opened 2017-05-23 15:01 UTC by johnnychen

* 增加webstorm目录名称被更改时的用例
* 增加复杂项目能力的支持

### 复杂项目定义：

* 项目根目录仅仅用来组织代码结构，根目录非node目录
* 根目录中具有n个子node工程

常用在node-server和static-server同时开发的场景，我们一个项目工程里两个node应用1个静态资源应用（已经简化，最多时3个静态资源应用）

2017-05-23 16:02 UTC, atian25 requested changes
thanks~

2017-05-23 16:02 UTC, atian25 commented on lib/command.js
> +    for(let pckInfo of configs){
prefer `pkgInfo`

2017-05-23 16:02 UTC, atian25 commented on lib/command.js
> +        pckInfo.____webstorm_disable_index_sub_module = moduleName;
just use `pkgInfo.moduleName`?

2017-05-23 16:02 UTC, atian25 commented on lib/command.js
> +    subModule && (BASE_PATH = `${BASE_PATH}/${subModule}`);
use `if` not `&&`

2017-05-23 16:02 UTC, atian25 commented on package.json
> +  "name": "cathay-webstorm-disable-index",
should not change name

2017-05-23 16:02 UTC, atian25 commented on package.json
> +  "version": "1.2.0",
`version` should not change at PR, it will change at `release time`

2017-05-23 16:02 UTC, atian25 commented on History.md
> +1.2.0 / 2017-05-23
`History.md` should not change at PR, it will change at `release time`

2017-05-23 16:02 UTC, atian25 commented on README.md
> +```
add `bash` after `

2017-05-23 16:02 UTC, atian25 commented on package.json
> +    "del": "^2.2.2",
prefer use https://github.com/isaacs/rimraf

2017-05-24 12:58 UTC, johnnychen commented on lib/command.js
> +        pckInfo.____webstorm_disable_index_sub_module = moduleName;
change to pkgInfo.__moduleName？

2017-05-25 00:09 UTC, atian25 approved these changes
still some point, but not matter, I will modify it after merge, thanks.

2017-05-25 00:10 UTC, merged

2017-05-25 00:45 UTC, atian25 commented
landed at 1.2.0

2017-05-25 02:06 UTC, johnnychen commented
ok, thks